#ifndef ROGALUNAROUTECORE_GLOBAL_H
#define ROGALUNAROUTECORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNAROUTECORE_LIBRARY)
#define ROGALUNAROUTECORE_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNAROUTECORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNAROUTECORE_GLOBAL_H
